#!/usr/bin/env bash
set -euo pipefail

ENV_DIR="${HOME}/.config/longwei-site"
ENV_FILE="${ENV_DIR}/deploy.env"

mkdir -p "${ENV_DIR}"
umask 077

if [[ -f "${ENV_FILE}" ]]; then
  echo "Config already exists: ${ENV_FILE}"
  echo "Edit it directly if you need to change values."
  exit 0
fi

cat >"${ENV_FILE}" <<'EOF'
# Aliyun credentials used by deploy scripts.
# NOTE: rotate this AccessKey regularly.
ALIYUN_ACCESS_KEY_ID=
ALIYUN_ACCESS_KEY_SECRET=

# Site source folder (local).
SOURCE_DIR=${HOME}/longwei-dev

# OSS bucket for static website files.
OSS_BUCKET=longwei-org-cn-site-20260226205642
OSS_REGION=cn-hongkong

# CDN config.
CDN_API_REGION=cn-hangzhou
CDN_DOMAINS=www.longwei.org.cn,longwei.org.cn

# Certificate files generated by acme.sh (ECC).
CERT_FULLCHAIN=${HOME}/.acme.sh/longwei.org.cn_ecc/fullchain.cer
CERT_KEY=${HOME}/.acme.sh/longwei.org.cn_ecc/longwei.org.cn.key
EOF

chmod 600 "${ENV_FILE}"
echo "Created: ${ENV_FILE}"
echo "Fill in ALIYUN_ACCESS_KEY_ID and ALIYUN_ACCESS_KEY_SECRET, then run deploy."
